#\!/bin/bash
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_92_with_AMPR.root EDM_SLHC_extr_ELE_92_with_FIT.root EDM_SLHC_extr_ELE_92_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_92 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_93_with_AMPR.root EDM_SLHC_extr_ELE_93_with_FIT.root EDM_SLHC_extr_ELE_93_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_93 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_94_with_AMPR.root EDM_SLHC_extr_ELE_94_with_FIT.root EDM_SLHC_extr_ELE_94_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_94 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_95_with_AMPR.root EDM_SLHC_extr_ELE_95_with_FIT.root EDM_SLHC_extr_ELE_95_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_95 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_96_with_AMPR.root EDM_SLHC_extr_ELE_96_with_FIT.root EDM_SLHC_extr_ELE_96_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_96 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_97_with_AMPR.root EDM_SLHC_extr_ELE_97_with_FIT.root EDM_SLHC_extr_ELE_97_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_97 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_98_with_AMPR.root EDM_SLHC_extr_ELE_98_with_FIT.root EDM_SLHC_extr_ELE_98_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_98 /data/viret/AMProc/TMP_100_test_ele
/gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3/src/L1Trigger/TrackFindingAM/test/batch/PR_processor_parallel.sh  FIT /data/viret/AMProc/TMPDAT_100_test_ele/EDM_SLHC_extr_ELE_99_with_AMPR.root EDM_SLHC_extr_ELE_99_with_FIT.root EDM_SLHC_extr_ELE_99_extr.root 2000 srm://lyogrid06.in2p3.fr//dpm/in2p3.fr/home/cms/data/store/user/sviret/SLHC/PR/100_test_ele /gridgroup/cms/viret/SLHC/CMSSW_10_0_0_pre3 auto:run2_mc EDM_SLHC_extr_ELE_99 /data/viret/AMProc/TMP_100_test_ele
