#\!/bin/bash
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_42_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_43_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_44_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_45_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_46_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_47_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_48_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_49_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_5_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_50_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_51_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_53_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_54_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_55_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_56_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_57_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_58_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_59_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_6_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_60_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_61_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_62_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_63_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_64_*root
