#\!/bin/bash
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_68_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_7_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_70_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_71_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_72_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_73_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_74_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_75_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_76_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_77_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_78_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_79_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_8_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_80_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_81_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_83_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_84_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_85_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_86_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_87_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_88_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_89_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_90_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_91_*root
