#\!/bin/bash
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_145_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_146_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_147_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_148_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_149_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_15_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_151_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_153_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_154_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_155_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_156_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_159_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_16_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_160_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_161_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_162_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_164_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_165_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_166_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_167_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_168_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_169_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_170_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_171_*root
