#\!/bin/bash
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_122_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_123_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_124_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_125_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_126_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_127_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_128_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_129_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_13_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_130_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_131_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_132_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_133_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_134_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_135_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_136_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_137_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_138_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_139_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_14_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_140_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_142_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_143_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_144_*root
