#\!/bin/bash
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_172_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_173_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_174_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_175_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_176_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_178_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_179_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_180_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_181_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_182_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_183_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_185_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_186_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_187_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_189_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_19_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_190_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_191_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_192_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_193_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_194_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_196_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_197_*root
cd /data/viret/AMProc/TMPDAT_100_test_ele
rm *EDM_SLHC_extr_ELE_198_*root
